version: '3'

services:
  db:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    volumes:
      - ./etc/backups:/backups
    env_file:
      - ./.env
    restart: always
    expose:
      - "5432"

  redis:
    image: redis:5.0.5-alpine
    restart: always
    expose:
      - "6379"

  wsgiserver:
    build:
      context: .
      dockerfile: ./compose/wsgiserver/Dockerfile
    restart: always
    expose:
      - "8000"
    volumes:
      - backend-static:/project/CoursesManager/static
      - project:/project/CoursesManager

  asgiserver:
    build:
      context: .
      dockerfile: ./compose/asgiserver/Dockerfile
    volumes:
      - project:/project/CoursesManager
    restart: always
    expose:
      - "9000"

  nginx:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    restart: always
    ports:
      - "80:80"
    volumes:
      - backend-static:/project/CoursesManager/static
    depends_on:
      - wsgiserver
      - asgiserver

volumes:
  backend-static:
  project:

