# Generated by Django 2.2.2 on 2019-07-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='ФИО'),
        ),
    ]
