# Generated by Django 2.2.2 on 2019-07-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(help_text='Номер телефона, без кода страны. Например: 9123456789', max_length=20, unique=True, verbose_name='Номер телефона'),
        ),
    ]
