# Generated by Django 2.2.2 on 2019-07-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название курса')),
                ('date_start', models.DateField(verbose_name='Дата начала курсов')),
                ('expiration_date', models.DateField(verbose_name='Дата окончания курсов')),
                ('dropped_out_students', models.ManyToManyField(blank=True, related_name='dropped_out_from_course', to='students.Student', verbose_name='Выбыли с курса')),
                ('students', models.ManyToManyField(blank=True, related_name='courses', to='students.Student', verbose_name='Студенты')),
                ('teachers', models.ManyToManyField(blank=True, related_name='courses', to='teachers.Teacher', verbose_name='Преподаватели')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
