# Generated by Django 2.2.2 on 2019-07-24 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('teachers', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование лекции')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('date_start', models.DateTimeField(verbose_name='Дата/Время начала')),
                ('link_token', models.CharField(max_length=32, unique=True, verbose_name='Токен лекции')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='courses.Course', verbose_name='Курс')),
                ('dropped_out_students', models.ManyToManyField(blank=True, related_name='dropped_out_from_lectures', to='students.Student', verbose_name='Заблокирован доступ для')),
                ('register_students', models.ManyToManyField(blank=True, related_name='lectures', to='students.Student', verbose_name='Зарегистрированные на лекцию')),
                ('teachers', models.ManyToManyField(blank=True, related_name='lectures', to='teachers.Teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Лекция',
                'verbose_name_plural': 'Лекции',
            },
        ),
        migrations.CreateModel(
            name='AttendanceLecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата/Время')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marked_students', to='lectures.Lecture', verbose_name='Лекция')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attended_lectures', to='students.Student', verbose_name='Студент')),
            ],
        ),
        migrations.AddConstraint(
            model_name='attendancelecture',
            constraint=models.UniqueConstraint(fields=('lecture', 'student'), name='unique_attendance_lecture'),
        ),
    ]
