# Generated by Django 2.2.2 on 2019-07-25 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancelecture',
            options={'verbose_name': 'Отмеченный студент на лекции', 'verbose_name_plural': 'Отмеченные студенты на лекции'},
        ),
    ]
