# Generated by Django 2.2.2 on 2019-07-26 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_auto_20190726_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='duration',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Продолжительность лекции'),
            preserve_default=False,
        ),
    ]
